consumer/config/routes.rb
Rails.application.routes.draw do
  resources :cats, only: [:index, :new, :create, :destroy]
end

consumer/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

consumer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

consumer/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = ANIMALS.cats.list
  end

  def create
    ANIMALS.cats.create(cat_params)
    redirect_to cats_path
  end

  def destroy
    ANIMALS.cats.delete(params[:id])
    redirect_to cats_path
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :age)
  end
end

consumer/app/helpers/application_helper.rb
module ApplicationHelper
end

consumer/app/views/cats/index.html.erb
<h1>Cats</h1>
<%= link_to 'Add', new_cat_path %>
<ul>
  <% @cats.each do |cat| %>
    <li>
      <%= cat.name %> (<%= cat.age %>)
      <%= link_to 'Remove', cat_path(cat.id), method: :delete, confirm: 'Sure?' %>
    </li>
  <% end %>
</ul>

consumer/app/views/cats/new.html.erb
<%= form_for :cat, url: cats_path do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.number_field :age %>

  <%= f.submit %>
<% end %>

consumer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Groomer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>